name: Minify And Publish
on:
  push:
    branches: [ main ]
  workflow_dispatch:
    
permissions:
  contents: read
  pages: write
  id-token: write
  deployments: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: HTML/CSS/JS Minifier
        uses: docker://devatherock/minify-js:1.0.3
        with:
          add_suffix: false
          
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: tz
          directory: .
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
